name: meili_flutter
description: Meili Flutter plugin
version: 0.1.0+1

homepage: https://github.com/meili-travel-tech/flutter_meili
repository: https://github.com/meili-travel-tech/flutter_meili
issue_tracker: https://github.com/meili-travel-tech/flutter_meili/issues

environment:
    sdk: '>=3.4.0 <4.0.0'
    flutter: '>=1.20.0'

flutter:
    plugin:
        platforms:
            android:
                default_package: meili_flutter_android
            ios:
                default_package: meili_flutter_ios

dependencies:
    flutter:
        sdk: flutter
    meili_flutter_android: ^0.1.0
    meili_flutter_ios: ^0.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    mocktail: ^1.0.4
    plugin_platform_interface: ^2.1.8
    very_good_analysis: ^6.0.0
