name: meili_flutter_android
description: Android implementation of the meili_flutter plugin
version: 0.1.0+1

homepage: https://github.com/meili-travel-tech/flutter_meili

environment:
    sdk: '>=3.4.0 <4.0.0'
    flutter: '>=1.20.0'

flutter:
    plugin:
        implements: meili_flutter
        platforms:
            android:
                package: com.example.verygoodcore
                pluginClass: MeiliFlutterPlugin
                dartPluginClass: MeiliFlutterAndroid

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    plugin_platform_interface: ^2.1.8
    very_good_analysis: ^6.0.0
